#!/usr/bin/env python
"""
Executable script for running statick against a single package.
"""

import sys
from statick_tool.args import Args
from statick_tool.statick import Statick


def main():
    """
    Run statick.
    """
    args = Args("Statick tool")
    args.parser.add_argument("path", help="Path of package to scan")

    statick = Statick(args.get_user_paths())
    statick.gather_args(args.parser)
    parsed_args = args.get_args()

    path = parsed_args.path
    issues = statick.run(path, parsed_args)
    found_issue = False
    for tool in issues.values():
        if len(tool) > 0:
            found_issue = True
    if issues is None or found_issue:
        sys.exit(1)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()
