levels:
  dockerfilelint:
    discovery:
      dockerfile:
        flags: ""
    tool:
      dockerfilelint:
        flags: ""

  dockerfile-lint:
    discovery:
      dockerfile:
        flags: ""
    tool:
      dockerfile-lint:
        flags: ""

  hadolint:
    discovery:
      dockerfile:
        flags: ""
    tool:
      hadolint:
        flags: ""

  tooling:
    discovery:
      dockerfile:
        flags: ""
    tool:
      dockerfilelint:
        flags: ""
      dockerfile-lint:
        flags: ""
      hadolint:
        flags: ""

  tooling_with_pylint:
    inherits_from:
      - "tooling"
    discovery:
      python:
        flags: ""
    tool:
      pylint:
        flags: "--good-names=f,i,j,k,x,y,z,ex,_"
