name: Black Formatting

on: [pull_request, push]  # NOLINT

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2  # NOLINT

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install black

    - name: Test with black
      run: |
        black --check --diff
              --exclude tests/plugins/tool/black_tool_plugin/valid_package/format_errors.py
              statick statick_ws statick_tool tests
